{% set name = "pyparted" %}
{% set version = "3.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/e7/53/b02306f89dc3eaf949659e8814545cde575867bc0175f60361809af7f71a/pyparted-3.13.0.tar.gz
  sha256: 443b59eb9ac63b8ca87094e02376646e172c7ea075f955f105889ca3485b06fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pkg-config
    - setuptools
    - parted
    - pip
    - python
    - setuptools
    - wheel
  run:
    - parted
    - python

about:
  home: https://github.com/dcantrell/pyparted/
  summary: Python bindings for GNU parted
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Geertsky
