package:
  name: parted
  version: "{{ GIT_DESCRIBE_TAG|replace('-','_') }}.{{ GIT_BUILD_STR|replace('-','_') }}"

source:
  git_url: https://github.com/Distrotech/parted
  git_depth: 1

requirements:
  host:
  - python=3.11
  build:
    - git
    - {{ compiler('c') }}
    #- asciidoctor
    - automake
    - autoconf>=2.64
    - cryptsetup
    - e2fsprogs
    - findutils
    - gettext
    - gzip
    #- json-c
    - kernel-headers_linux-64
    - libdevmapper
    #- libgcrypt
    - libnsl
    - libtool
    - libuuid
    #- libssh
    - make 
    #- openssl >=0.9.8
    - perl
    - rsync
    - tar
    - texinfo
    #- popt
    - pkgconfig
    - util-linux

test:
  commands:
    - parted --help

about:
  home: http://www.gnu.org/software/parted
  license: GPL-3.0 license
  doc_url: http://www.gnu.org/software/parted/manual/parted.html
